# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:47
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('surname', models.TextField(max_length=120)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=app.models.upload_location, width_field='width_field')),
                ('bio', models.TextField()),
                ('courser', models.TextField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
