# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:25
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171114_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=123)),
                ('teacher', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('course', models.TextField(max_length=15)),
                ('the_elder', models.TextField(max_length=12)),
                ('students', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('surname', models.TextField(max_length=120)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=app.models.upload_location, width_field='width_field')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('surname', models.TextField(max_length=120)),
                ('image', models.ImageField(blank=True, height_field='150px', null=True, upload_to=app.models.upload_location, width_field='150px')),
                ('bio', models.TextField()),
                ('courser', models.TextField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
